# Introduction {-}
Dans un contexte agronomique actuel de réduction de l'utilisation des pesticides ou de réchauffement climatique, analyser et comprendre les bases génétiques de l'adaptation des organismes aux méthodes de luttes qui leurs sont opposées ou à l’évolution de leur environnement est un enjeu majeur des recherches de ces dernières années.

Les études d'associations pangénomiques (GWAS en anglais pour genome-wide association study) adossées aux techniques de séquençage haut débit (NGS) permettant le séquençage de génome complet, sont un outil de choix pour ce type d’analyse. L’étude au niveau populationnel demandant le séquençage d’un grand nombre d’individus, les couts d’analyses étaient initialement très élevés et ces études étaient souvent réservées aux organismes dit ‘‘modèles’’, humain en tête. Néanmoins il a été démontré depuis, que le séquençage en pool d’individus (poolseq) c’est-à-dire en mélangeant de manière équimolaire l’ADN d’un grand nombre d’individus (50 à 100) issus d’une même population permettait non seulement de réduire drastiquement les couts puisqu’on ne réalise qu’un seul séquençage mais aussi que la découverte des points de mutations (SNP) et l’estimation de leur fréquence allélique étaient souvent plus efficaces et précises [@futschik_next_2010]. Parmi les logiciels à même d’analyser ces fréquences alléliques on compte Baypass [@gautier_genome-wide_2015] qui évalue par une approche baysienne, la différenciation des SNP en liaison avec une covariable environnementale en tenant compte de la structure et de la parenté entre les populations en estimant la covariance (Ω) des fréquences alléliques. Baypass 2.3 a la particularité supplémentaire de pouvoir calculer un contraste des fréquences alléliques entre deux groupes de populations caractérisés par un caractère binaire, sensible ou résistant par exemple. 

La documentation disponible de BayPass 2.3 décrit par le menu les algorithmes de fonctionnement et les différents paramètres du logiciel mais reste néanmoins, et assez logiquement, succincte sur les étapes en amont et en aval. A ma connaissance un seul tutoriel est disponible sur le web [@nielsen_pool-seq_2020] et décrit de manière plus détaillée la préparation des données brutes et l’analyse en mode « poolseq » de Baypass, mais il nécessite des bases quelque peu avancées de codage sous R et en environnement bash. Si les bio-informaticiens chevronnés ne rencontreront pas de difficultés particulières, il n’en va pas forcément de même pour bon nombre d’agents que les orientations des recherches associées à la baisse des coûts de séquençage ont aiguillé vers les voies de la génomique. Cet article a pour but de détailler les différentes étapes d’une analyse de type GWAS/poolseq avec le logiciel BayPass 2.3 et d’éclairer les points qui sont habituellement peu explicités car considérés comme évident.
