# Conversion du pooldata en fichiers d'entrées pour BayPass {-}
La fonction **_pooldata2genobaypass_** (Chunk \@ref(exr:chunk4)) convertit l'ogbjet **_pooldata_** en fichier d'entrée pour BayPass:

```{exercise, chunk4}
<span style="color:darkgreen">Création des fichiers input de BayPass</span>
```
<p style="font-family: calibri; font-size:11pt; font-style:italic; color:darkgreen">
  
</p>
```{r Input-BayPass, class.source='bg-chunk', class.output='bg-output', message=FALSE}
pooldata2genobaypass(pooldata, writing.dir = path_input, subsamplesize = -1, subsamplingmethod = "thinning")
```
On récupère dans le répertoire **_path_input_** trois fichiers: un fichier "**_genobaypass_**" qui contient les données filtrées de génotypage, un fichier "**_snpdet_**" qui contient la liste des positions correspondantes et un fichier "**_poolsize_**", qui est une copie de l'objet **_psizes_**.

## Design de l’analyse BayPass {-}
Deux fichiers de paramétrages au format texte/tabulation peuvent être créés en fonction de l'analyse envisagé:
Le premier fichier "**_ecotype_**" (Table \@ref(def:table1)) identifie les covariables quantitatives écologiques de chaque population, avec une covariable par ligne et autant de lignes que de covariables à analyser. Seules sont acceptées les valeurs numériques graduées (taille, poids, mortalité ...).

```{definition, table1}
<span style="color:darkgreen">Example de constitution d'un fichier **_ecotype_**</span>
```
<p style="font-family: calibri; font-size:11pt; font-style:italic; color:darkgreen">
   Chaque ligne correspond à une covariable quantitative, chaque colonne correspond à une population.
</p>

<table>
  <tr>
    <td>25</td>
    <td>48.5</td>
    <td>96.2</td>
    <td>17</td>
    <td>15.3</td>
    <td>...</td>
  </tr>
  <tr>
    <td>4.75</td>
    <td>0.53</td>
    <td>0.27</td>
    <td>-0.86</td>
    <td>-0.61</td>
    <td>...</td>
  </tr>
  <tr>
    <td>43.90</td>
    <td>44.37</td>
    <td>44.29</td>
    <td>47.36</td>
    <td>47.86</td>
    <td>...</td>
  </tr>
</table>

Le deuxième fichier **_contraste_** (Table \@ref(def:table2))contient les covariables qualitatives (petit, chaud, resistant...), il permet d'identifier l’appartenance de chaque population à un groupe qualitatif soit référence (-1), un groupe candidat (1) ou aucun des deux groupes (0). Une ligne par combinaison de contraste.

```{definition, table2}
<span style="color:darkgreen">Example de constitution d'un fichier **_contraste_**</span>
```
<p style="font-family: calibri; font-size:11pt; font-style:italic; color:darkgreen">
   Chaque ligne correspond à une analyse binaire de comparaison des fréquences alléliques de 2 groupes de population.<br>
   Sur la ligne 1 le groupe composé des population 1 et 2 est comparé au groupe des populations 3,4 et 5.<br>
   Sur la ligne 2 le groupe composé des population 1 et 2 est comparé au groupe des populations 4 et 5, la population 3 est exclue de l'analyse.
   Etc...
</p>

<table>
  <tr>
    <td>1</td>
    <td>1</td>
    <td>-1</td>
    <td>-1</td>
    <td>-1</td>
    <td>...</td>
  </tr>
  <tr>
    <td>1</td>
    <td>1</td>
    <td>0</td>
    <td>-1</td>
    <td>-1</td>
    <td>...</td>
  </tr>
  <tr>
    <td>0</td>
    <td>1</td>
    <td>-1</td>
    <td>-1</td>
    <td>0</td>
    <td>...</td>
  </tr>
</table>

Ces fichiers seront aussi transférés sur le cluster de calcul.

IMPORTANT : Les analyses BayPass sont relativement longues (plusieurs heures) mais l'analyses conjointes de plusieurs covariables a un impact relativement faible sur le temps de calcul final, dès lors il est très rentable de multiplier les analyses de covariables en ajoutant autant de lignes que nécessaires dans ces fichiers de paramétrages plutôt que de relancer une analyse complète pour chacune d’entre elles. 

## Subsampling {-}
Copier les fichiers **_genobaypass, snpdet, poolsize, contraste, ecotype_** sur le cluster de calcul.
La découpe en sous jeux de données des fichier genobaypass et snpdet se fait sous Bash avec une commande sed par exemple (Script \@ref(exm:script3)).

```{example, script3}
<span style="color:darkgreen">Exemple d'une commande de subsampling.</span>
```
<p style="font-family: calibri; font-size:11pt; font-style:italic; color:darkgreen">
   La commande **_sed_** prélève une ligne toutes les 10 et les copies dans un fichier **_.sub_** et s'exécute 10 fois pour balayer tous le fichier initial et créer ainsi 10 fichiers de sous-jeux de données.
</p>
```{bash scr3, eval=FALSE, class.source='bg-linux'}
for i in {1..10}; do sed -n "$i~10p" genobaypass > genobaypass.sub$i; sed -n "$i~10p" snpdet > snpdet.sub$i; done
```
Le nombre de fichiers **_.sub_** à créer dépend du nombre total de SNP à analyser, une taille finale de 80 000 à 120 000 SNPs par fichier de sous-jeux de données est un bon compromis entre qualité d'analyse et temps de calcul.