# Baypass : l’analyse poolseq {-}

La commande est la même pour les différents modèles employés par BayPass (Script \@ref(exm:script4)), ce sont les fichiers optionnels qui définissent le modèle :
l'option poolsize active le mode Pool-Seq, pour le core model, seuls les fichiers genobaypass et snpdet sont nécessaires, on peut néanmoins faire une analyse de la statistique de contraste C2 avec le fichier de covariable qualitative **_contraste_**.
Le modèle standard est activé par l'option **_-efile_**, le fichier de covariable quantitative **_ecotype_**.

Il est recommandé dans le cadre d’une analyse Pool-Seq d’utiliser et fixer le paramètre -d0yij à 1/5e de la valeur la plus faible du poolsize. (voir page 22 et 39 du manuel de BayPass).
Tous les fichiers de résultats cibleront le dossier dans lequel se trouve le script.

```{example, script4}
<span style="color:darkgreen">Exemple d'un script bash pour lancer une analyse BayPass</span>
```
<p style="font-family:calibri; font-size:11pt; font-style:italic; color:darkgreen">
   Les sous-jeux de données sont analysés en parallèle 
</p>
```{bash scr4, eval=FALSE, class.source='bg-linux'}
#!/bin/bash
#SBATCH --array=0-9        #création de l'array: un élément/indice par job prévu (indice base 0)
#SBATCH --cpus-per-task=2   #nbr de core par job
#SBATCH --mem-per-cpu=2G    #mémoire partagée par tous les cores

module purge
module load statistics/R/4.2.2
module load bioinfo/BayPass/2.4
module load compilers/intel/2023.0.0    #pour i_baypass


#définition du chemin ciblant les fichiers genobaypass et snpdet
my_path='/../Input/'
FILES_R1=($(ls $my_path/genobaypass.sub* | sed -r 's/^.+\///'))
INPUT_F1=${FILES_R1[$SLURM_ARRAY_TASK_ID]}
OUTPUT=${FILES_R1[$SLURM_ARRAY_TASK_ID]/genobaypass/project.output}

i_baypass \
-gfile $my_path/$INPUT_F1 \                  #fichiers genobaypass.sub*
-poolsizefile $my_path/poolsize \            #active le mode poolseq
-d0yij 40 \                               #1/5e de la valeur la plus faible du poolsize
-seed 5001 \
-nthreads 2 \
-outprefix $OUTPUT \
```

Pour le modèle standard, il faut rajouter au script précédent le fichier contenant les covariables  quantitatives:
```{bash scr4.2, eval=FALSE, class.source='bg-linux'}
-efile $my_path/ecotype \                    #calcul des Bayes Factors: modèle standard & auxiliaire
-contrastfile $my_path/contrast \            #calcul du contraste C2: modèle core, standard & auxiliaire
```

Pour le modèle auxiliaire, il faut rajouter au script précédent en plus des fichiers covariables:
```{bash scr4.3, eval=FALSE, class.source='bg-linux'}
-auxmodel \                               #active le modèle auxiliaire
-omegafile $my_path/omega.mat \           #matrice Ω modèle standard (optionnel) & auxiliaire (obligatoire)
-auxPbetaprior 0.02 1.98                  #ajuste le Pi beta prior 
```